#pragma once

#include "PlatformMath.h"
#include "Vector2D.h"
#include "Vector3D.h"
#include "Vector4D.h"
#include "Color.h"
#include "Degrees.h"
#include "Radians.h"
#include "Matrix3D.h"
#include "Matrix4D.h"
#include "Quaternion.h"
#include "OBB.h"
#include "Plane.h"
#include "Sphere.h"
#include "Ray.h"
#include "Frustum.h"
#include "Intersection.h"